name: PyBuilder Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install pylint
        run: pip install pylint

      - name: Run pylint
        run: pylint src/main/python/helloworld.py

  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
           
      - name: Install PyBuilder
        run: | 
          python -m pip install --upgrade pip
          pip install pybuilder
     
      - name: Build and Test
        run: pyb

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: target/reports  

      - name: List Files  # Optional step
        run: |
          ls -R     
          
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: .
        args: >
          -Dsonar.organization=2023mt03024
          -Dsonar.projectKey=2023mt03024_pyb
          -Dsonar.python.coverage.reportPaths=target/reports/helloworld_coverage.xml
          -Dsonar.sources=src/main
          -Dsonar.test.exclusions=src/unittest/**
          -Dsonar.tests=tests/
          -Dsonar.verbose=true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
